- name: exercitiu despre bucle, conditii, portabilitate
  hosts: all

  tasks:
    - name: check if cron is running
      ansible.builtin.command: systemctl is-active cron
      register: cron_state # saves the output of the module that ran
      changed_when: false # doesn't mark this task as changed no matter what it does
      failed_when: false # doesn't mark this task as failed no matter the return code
      check_mode: false

    - name: this should never print
      ansible.builtin.debug:
        msg: "very very secret info"
      when: ( secret_var | default('')) == "anomaly"
