---
- name: Instalez fail2ban
  ansible.builtin.package:
    name: fail2ban
    state: present

- name: Aplic configuratia jail.local
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
  notify: Restart fail2ban

- name: Ma asigur ca fail2ban e pornit si activat la boot
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
